name: MultiExperience
main: org.meowcat.MultiExperience.Main
author: MeowCat Studio MlgmXyysd
version: 1.0.0
commands:
  multiexp:
    permission: multiexp.admin
    description: Multi Experience Plugin Info
    usage: /<command> enable [multiple] [minute]
permissions:
  multiexp.admin:
    default: op